# Generated by Django 5.1.7 on 2026-07-11 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allocation', '0001_initial'),
        ('instruments', '0001_initial'),
        ('oms', '0001_initial'),
        ('portfolios', '0001_initial'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderintentattribution',
            name='order_intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributions', to='oms.orderintent'),
        ),
        migrations.AddField(
            model_name='orderintentattribution',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='strategies.tradingstrategy'),
        ),
        migrations.AddField(
            model_name='portfolioflow',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flows', to='portfolios.tradingportfolio'),
        ),
        migrations.AddField(
            model_name='allocationrun',
            name='flow',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_run', to='allocation.portfolioflow'),
        ),
        migrations.AddField(
            model_name='rebalancepolicy',
            name='portfolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rebalance_policy', to='portfolios.tradingportfolio'),
        ),
        migrations.AddField(
            model_name='rebalancerun',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='allocation.rebalancepolicy'),
        ),
        migrations.AddField(
            model_name='rebalancerun',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolios.tradingportfolio'),
        ),
        migrations.AddField(
            model_name='strategycapitalsnapshot',
            name='allocation_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capital_snapshots', to='allocation.allocationrun'),
        ),
        migrations.AddField(
            model_name='strategycapitalsnapshot',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='strategies.tradingstrategy'),
        ),
        migrations.AddField(
            model_name='targetportfolioposition',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instruments.instrument'),
        ),
        migrations.AddField(
            model_name='targetportfolioposition',
            name='rebalance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='allocation.rebalancerun'),
        ),
        migrations.AddConstraint(
            model_name='orderintentattribution',
            constraint=models.UniqueConstraint(fields=('order_intent', 'strategy'), name='unique_intent_strategy_attribution'),
        ),
        migrations.AddConstraint(
            model_name='targetportfolioposition',
            constraint=models.UniqueConstraint(fields=('rebalance', 'instrument'), name='unique_rebalance_target'),
        ),
    ]
