# Generated by Django 5.1.7 on 2026-07-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0008_instance_only'),
        ('portfolio_optimization', '0003_operation_idempotency_state'),
        ('portfolios', '0002_position_realized_pnl'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rebalancerun',
            index=models.Index(fields=['portfolio', 'status', '-created_at'], name='rebalance_port_status_idx'),
        ),
        migrations.AddIndex(
            model_name='rebalancerun',
            index=models.Index(fields=['status', 'mode', 'phase'], name='rebalance_recovery_idx'),
        ),
    ]
