# Generated by Django 5.1.7 on 2026-07-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway_service', '0002_command_leases'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gatewayevent',
            index=models.Index(fields=['acknowledged', 'created_at'], name='gateway_event_ack_idx'),
        ),
        migrations.AddIndex(
            model_name='gatewayhealthsnapshot',
            index=models.Index(fields=['-created_at'], name='gateway_health_time_idx'),
        ),
    ]
