services:
  flink-jobmanager:
    ports:
      - "127.0.0.1:8081:8081"

  paper-ibkr-gateway:
    platform: linux/amd64
    environment:
      BROKER_ADAPTER: ${LOCAL_PAPER_GATEWAY_ADAPTER}
      IBC_TRADING_MODE: ${IBC_TRADING_MODE}
      IBC_2FA_TIMEOUT: ${IBC_2FA_TIMEOUT}
      IBKR_CLIENT_ID: ${IBKR_CLIENT_ID}
      IBC_AUTO_RESTART_TIME: ${IBC_AUTO_RESTART_TIME}
      GATEWAY_CONTRACT_SEARCH_MAX_RESULTS: ${GATEWAY_CONTRACT_SEARCH_MAX_RESULTS}
      GATEWAY_IBKR_REQUEST_TIMEOUT_SEARCH_CONTRACTS_SECONDS: ${GATEWAY_IBKR_REQUEST_TIMEOUT_SEARCH_CONTRACTS_SECONDS}
      GATEWAY_IBKR_REQUEST_TIMEOUT_QUALIFY_SECONDS: ${GATEWAY_IBKR_REQUEST_TIMEOUT_QUALIFY_SECONDS}
    ports:
      - "127.0.0.1:8082:8080"