# Generated by Django 5.1.7 on 2026-07-16 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_construction', '0004_alter_goalstrategyassignment_created_strategy_instance'),
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliogoalallocation',
            name='accepted_recommendation_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_goals', to='research.goalrecommendationrun'),
        ),
        migrations.AddField(
            model_name='portfoliogoalallocation',
            name='construction_source',
            field=models.CharField(choices=[('MANUAL_OPTIMIZER', 'Manual optimizer'), ('ACCEPTED_RECOMMENDATION', 'Accepted recommendation')], default='MANUAL_OPTIMIZER', max_length=32),
        ),
    ]
