# Generated by Django 5.1.7 on 2026-07-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketdatafetchrun',
            name='response_metadata',
            field=models.JSONField(default=dict),
        ),
    ]
