# Generated by Django 5.1.7 on 2026-07-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0009_rebalancerun_rebalance_port_status_idx_and_more'),
        ('instruments', '0003_exact_contract_identity'),
        ('oms', '0007_instance_only'),
        ('portfolios', '0002_position_realized_pnl'),
        ('strategies', '0006_remove_legacy_strategy'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'updated_at'], name='order_status_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['broker_order_id'], name='order_broker_id_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['broker_permanent_id'], name='order_permanent_id_idx'),
        ),
        migrations.AddIndex(
            model_name='orderintent',
            index=models.Index(fields=['portfolio', '-created_at'], name='intent_portfolio_created_idx'),
        ),
        migrations.AddIndex(
            model_name='orderintent',
            index=models.Index(fields=['operation_status', 'eligible', 'created_at'], name='intent_operation_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='orderintent',
            index=models.Index(fields=['rebalance', 'side'], name='intent_rebalance_side_idx'),
        ),
        migrations.AddIndex(
            model_name='orderintent',
            index=models.Index(fields=['strategy_instance', '-created_at'], name='intent_strategy_created_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['order', 'occurred_at'], name='order_history_time_idx'),
        ),
    ]
