# Generated by Django 5.1.7 on 2026-07-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broker_gateway", "0003_brokergatewaysessionsecret_brokersessionaccount_and_more"),
        ("execution", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokerCommand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("internal_order_id", models.CharField(db_index=True, max_length=64)),
                ("command_type", models.CharField(choices=[("PLACE", "Place"), ("MODIFY", "Modify"), ("CANCEL", "Cancel")], max_length=8)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("request_payload", models.JSONField(default=dict)),
                ("request_hash", models.CharField(db_index=True, max_length=64)),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("CLAIMED", "Claimed"), ("SENDING", "Sending"), ("RETRY", "Retry"), ("UNCERTAIN", "Uncertain"), ("ACKNOWLEDGED", "Acknowledged"), ("FAILED", "Failed")], default="PENDING", max_length=16)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("response_payload", models.JSONField(default=dict)),
                ("last_error", models.CharField(blank=True, max_length=1000)),
                ("uncertainty_reason", models.CharField(blank=True, max_length=1000)),
                ("broker_order_id", models.CharField(blank=True, max_length=64)),
                ("broker_permanent_id", models.CharField(blank=True, max_length=64)),
                ("gateway_command_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gateway_session", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="broker_commands", to="broker_gateway.brokergatewaysession")),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="broker_commands", to="oms.order")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["status", "next_attempt_at", "created_at"], name="broker_cmd_dispatch_idx"),
                    models.Index(fields=["gateway_session", "internal_order_id"], name="broker_cmd_session_order_idx"),
                ],
            },
        ),
    ]
