# Generated by Django 5.1.7 on 2026-07-11 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('strategy_type', models.CharField(choices=[('fixed_weight', 'fixed_weight'), ('sma_trend', 'sma_trend'), ('rsi_mean_reversion', 'rsi_mean_reversion'), ('donchian_breakout', 'donchian_breakout'), ('volatility_target_momentum', 'volatility_target_momentum')], max_length=40)),
                ('version', models.PositiveIntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('schedule', models.CharField(default='manual', max_length=64)),
                ('configuration', models.JSONField(default=dict)),
                ('allocated_capital', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('maximum_target_weight', models.DecimalField(decimal_places=6, default=1, max_digits=8)),
                ('kill_switch', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('universe', models.ManyToManyField(blank=True, to='instruments.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_hash', models.CharField(max_length=64)),
                ('configuration_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(default='RUNNING', max_length=24)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='strategies.tradingstrategy')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=8, max_digits=12)),
                ('minimum_share', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('maximum_share', models.DecimalField(decimal_places=8, default=1, max_digits=12)),
                ('capacity', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('minimum_allocation', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('idle_cash', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolios.tradingportfolio')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='strategies.tradingstrategy')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=24)),
                ('high', models.DecimalField(decimal_places=8, max_digits=24)),
                ('low', models.DecimalField(decimal_places=8, max_digits=24)),
                ('close', models.DecimalField(decimal_places=8, max_digits=24)),
                ('volume', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instruments.instrument')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('instrument', 'timestamp'), name='unique_historical_bar')],
            },
        ),
        migrations.CreateModel(
            name='StrategyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_weight', models.DecimalField(decimal_places=8, max_digits=12)),
                ('rationale', models.CharField(blank=True, max_length=255)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instruments.instrument')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='strategies.strategyrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'instrument'), name='unique_run_target')],
            },
        ),
        migrations.AddConstraint(
            model_name='strategyrun',
            constraint=models.UniqueConstraint(fields=('strategy', 'input_hash'), name='unique_strategy_input'),
        ),
        migrations.AddConstraint(
            model_name='strategyallocation',
            constraint=models.UniqueConstraint(fields=('strategy', 'portfolio'), name='unique_strategy_allocation'),
        ),
    ]
