# Generated by Django 5.1.7 on 2026-07-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_exact_contract_identity'),
        ('portfolios', '0003_portfolioposition_portfolio_position_time_idx'),
        ('strategies', '0006_remove_legacy_strategy'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='strategyallocation',
            index=models.Index(fields=['portfolio', 'priority'], name='strategy_alloc_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyinstance',
            index=models.Index(fields=['enabled', 'state', 'instrument', 'timeframe'], name='strategy_active_input_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyrun',
            index=models.Index(fields=['strategy_instance', '-started_at'], name='strategy_run_latest_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyrun',
            index=models.Index(fields=['status', 'started_at'], name='strategy_run_status_idx'),
        ),
        migrations.AddIndex(
            model_name='strategytarget',
            index=models.Index(fields=['strategy_instance', 'status', '-created_at'], name='strategy_target_latest_idx'),
        ),
    ]
