# Generated by Django 5.1.7 on 2026-07-11 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.CharField(max_length=128, unique=True)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=24)),
                ('price', models.DecimalField(decimal_places=8, max_digits=24)),
                ('commission', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('executed_at', models.DateTimeField()),
                ('raw_event', models.JSONField(default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fills', to='oms.order')),
            ],
        ),
    ]
