# Generated by Django 5.1.7 on 2026-07-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(blank=True, null=True)),
                ('source_topic', models.CharField(max_length=128)),
                ('consumer_name', models.CharField(blank=True, max_length=128)),
                ('reason', models.CharField(max_length=255)),
                ('envelope', models.JSONField(default=dict)),
                ('replayed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReplayRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=128)),
                ('consumer_name', models.CharField(max_length=128)),
                ('from_timestamp', models.DateTimeField(blank=True, null=True)),
                ('to_timestamp', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='REQUESTED', max_length=16)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_name', models.CharField(max_length=128)),
                ('event_id', models.UUIDField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.JSONField(default=dict)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('consumer_name', 'event_id'), name='unique_consumed_event')],
            },
        ),
        migrations.CreateModel(
            name='StreamHealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=128)),
                ('metric', models.CharField(max_length=128)),
                ('status', models.CharField(default='UNKNOWN', max_length=24)),
                ('value', models.JSONField(default=dict)),
                ('observed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('component', 'metric'), name='unique_stream_health_metric')],
            },
        ),
    ]
