# Generated by Django 5.1.7 on 2026-07-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_bus', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deadletterevent',
            index=models.Index(fields=['replayed_at', 'created_at'], name='dead_letter_replay_idx'),
        ),
    ]
