# Generated by Django 5.1.7 on 2026-07-13 03:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def seed_plugins(apps, schema_editor):
    Definition = apps.get_model('strategies', 'StrategyDefinition')
    definitions = [
        ("RSI_MEAN_REVERSION", "RSI Mean Reversion", "RSIMeanReversionPlugin", ["LONG", "SHORT", "BOTH"],
         {"window":{"type":"integer","minimum":2},"entry_threshold":{"type":"number"},"exit_threshold":{"type":"number"},"direction":{"enum":["LONG","SHORT","BOTH"]}}),
        ("SMA_CROSSOVER", "SMA Crossover", "SMACrossoverPlugin", ["LONG", "SHORT", "BOTH"],
         {"fast_window":{"type":"integer","minimum":2},"slow_window":{"type":"integer","minimum":3},"direction":{"enum":["LONG","SHORT","BOTH"]}}),
        ("DONCHIAN_BREAKOUT", "Donchian Breakout", "DonchianBreakoutPlugin", ["LONG", "SHORT", "BOTH"],
         {"entry_window":{"type":"integer","minimum":2},"exit_window":{"type":"integer","minimum":2},"direction":{"enum":["LONG","SHORT","BOTH"]}}),
        ("VOLATILITY_TARGET_MOMENTUM", "Volatility-Target Momentum", "VolatilityTargetMomentumPlugin", ["LONG", "SHORT", "BOTH"],
         {"momentum_window":{"type":"integer","minimum":2},"volatility_window":{"type":"integer","minimum":2},"target_volatility":{"type":"number"},"maximum_weight":{"type":"number"},"direction":{"enum":["LONG","SHORT","BOTH"]}}),
        ("FIXED_WEIGHT_REBALANCE", "Fixed-Weight Rebalance", "FixedWeightPlugin", ["LONG", "SHORT", "BOTH"],
         {"direction":{"enum":["LONG","SHORT","BOTH"]}}),
    ]
    for key, name, class_name, directions, properties in definitions:
        Definition.objects.update_or_create(key=key, defaults={"name":name,"description":f"Built-in {name} plugin",
            "plugin_path":f"apps.strategies.plugins.builtin.{class_name}","input_requirements":[],
            "parameter_schema":{"type":"object","properties":properties},"supported_asset_types":["STK"],
            "supported_directions":directions,"supported_timeframes":["1m","5m","15m","1h","1d"],"enabled":True})
    OrderPolicy = apps.get_model('strategies', 'OrderPolicy')
    RiskPolicy = apps.get_model('strategies', 'StrategyRiskPolicy')
    OrderPolicy.objects.get_or_create(name="Default marketable limit")
    RiskPolicy.objects.get_or_create(name="Default long-only", defaults={"allow_short":False,"maximum_weight":"0.10"})


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
        ('portfolios', '0001_initial'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('order_type', models.CharField(default='LMT', max_length=16)),
                ('time_in_force', models.CharField(default='DAY', max_length=8)),
                ('limit_offset_bps', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('price_collar_bps', models.DecimalField(decimal_places=4, default=50, max_digits=10)),
                ('allow_market_order', models.BooleanField(default=False)),
                ('replace_after_seconds', models.PositiveIntegerField(default=60)),
                ('maximum_replacements', models.PositiveIntegerField(default=2)),
                ('cancel_at_session_end', models.BooleanField(default=True)),
                ('outside_regular_hours', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StrategyDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('plugin_path', models.CharField(max_length=255)),
                ('input_requirements', models.JSONField(default=list)),
                ('parameter_schema', models.JSONField(default=dict)),
                ('supported_asset_types', models.JSONField(default=list)),
                ('supported_directions', models.JSONField(default=list)),
                ('supported_timeframes', models.JSONField(default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StrategyRiskPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('maximum_weight', models.DecimalField(decimal_places=8, default='0.10', max_digits=10)),
                ('maximum_notional', models.DecimalField(decimal_places=8, default='100000', max_digits=24)),
                ('maximum_quantity', models.DecimalField(decimal_places=8, default='100000', max_digits=24)),
                ('allow_short', models.BooleanField(default=False)),
                ('configuration', models.JSONField(default=dict)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='strategyrun',
            name='context_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='strategyrun',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='strategyrun',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='strategyrun',
            name='source_data_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='strategyrun',
            name='triggering_event_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='strategytarget',
            name='confidence',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='strategytarget',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='strategytarget',
            name='direction',
            field=models.CharField(default='FLAT', max_length=16),
        ),
        migrations.AddField(
            model_name='strategytarget',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portfolios.tradingportfolio'),
        ),
        migrations.AddField(
            model_name='strategytarget',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='strategytarget',
            name='signal_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategytarget',
            name='signal_type',
            field=models.CharField(default='SET_TARGET', max_length=32),
        ),
        migrations.AddField(
            model_name='strategytarget',
            name='source_event_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='strategytarget',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=24),
        ),
        migrations.AddField(
            model_name='strategytarget',
            name='target_quantity',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='strategytarget',
            name='target_type',
            field=models.CharField(choices=[('WEIGHT', 'WEIGHT'), ('VALUE', 'VALUE'), ('QUANTITY', 'QUANTITY'), ('FLAT', 'FLAT')], default='WEIGHT', max_length=16),
        ),
        migrations.AddField(
            model_name='strategytarget',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='strategyrun',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='strategies.tradingstrategy'),
        ),
        migrations.AlterField(
            model_name='strategytarget',
            name='target_weight',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='StrategyInputRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_hash', models.CharField(max_length=64, unique=True)),
                ('timeframe', models.CharField(max_length=16)),
                ('input_type', models.CharField(choices=[('BAR', 'BAR'), ('INDICATOR', 'INDICATOR')], max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('parameters', models.JSONField(default=dict)),
                ('parameters_hash', models.CharField(max_length=64)),
                ('required_bar_fields', models.JSONField(default=list)),
                ('warmup_bars', models.PositiveIntegerField(default=0)),
                ('active_ref_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategy_input_requirements', to='instruments.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('universe', models.JSONField(blank=True, default=list)),
                ('timeframe', models.CharField(max_length=16)),
                ('parameters', models.JSONField(default=dict)),
                ('target_configuration', models.JSONField(default=dict)),
                ('execution_mode', models.CharField(choices=[('OBSERVE', 'OBSERVE'), ('SHADOW', 'SHADOW'), ('PAPER', 'PAPER')], default='SHADOW', max_length=16)),
                ('state', models.CharField(choices=[('FLAT', 'FLAT'), ('ENTRY_PENDING', 'ENTRY_PENDING'), ('PARTIALLY_LONG', 'PARTIALLY_LONG'), ('LONG', 'LONG'), ('EXIT_PENDING', 'EXIT_PENDING'), ('PARTIALLY_SHORT', 'PARTIALLY_SHORT'), ('SHORT', 'SHORT'), ('PAUSED', 'PAUSED'), ('BLOCKED', 'BLOCKED'), ('WARMING_UP', 'WARMING_UP'), ('ERROR', 'ERROR')], default='WARMING_UP', max_length=24)),
                ('enabled', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('state_data', models.JSONField(default=dict)),
                ('warmup_progress', models.PositiveIntegerField(default=0)),
                ('block_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='strategies.strategydefinition')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategy_instances', to='instruments.instrument')),
                ('legacy_strategy', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='strategy_instance', to='strategies.tradingstrategy')),
                ('order_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='strategies.orderpolicy')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategy_instances', to='portfolios.tradingportfolio')),
                ('risk_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='strategies.strategyriskpolicy')),
            ],
        ),
        migrations.AddField(
            model_name='strategyrun',
            name='strategy_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='strategies.strategyinstance'),
        ),
        migrations.AddField(
            model_name='strategytarget',
            name='strategy_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='strategies.strategyinstance'),
        ),
        migrations.CreateModel(
            name='StrategyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('configuration_snapshot', models.JSONField(default=dict)),
                ('parameter_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('strategy_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='strategies.strategyinstance')),
            ],
        ),
        migrations.CreateModel(
            name='StrategySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(max_length=32)),
                ('signal_time', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='signal', to='strategies.strategyrun')),
                ('strategy_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='strategies.strategyinstance')),
                ('strategy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='strategies.strategyversion')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyInputBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bindings', to='strategies.strategyinputrequirement')),
                ('strategy_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_bindings', to='strategies.strategyinstance')),
                ('strategy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_bindings', to='strategies.strategyversion')),
            ],
        ),
        migrations.AddField(
            model_name='strategyrun',
            name='strategy_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='strategies.strategyversion'),
        ),
        migrations.AddField(
            model_name='strategytarget',
            name='strategy_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='strategies.strategyversion'),
        ),
        migrations.CreateModel(
            name='StrategyAttributedPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('average_cost', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instruments.instrument')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolios.tradingportfolio')),
                ('strategy_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributed_positions', to='strategies.strategyinstance')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('strategy_instance', 'instrument', 'portfolio'), name='unique_strategy_attributed_position')],
            },
        ),
        migrations.AddConstraint(
            model_name='strategyinstance',
            constraint=models.UniqueConstraint(fields=('portfolio', 'name'), name='unique_strategy_instance_name'),
        ),
        migrations.AddConstraint(
            model_name='strategyversion',
            constraint=models.UniqueConstraint(fields=('strategy_instance', 'version'), name='unique_strategy_version'),
        ),
        migrations.AddConstraint(
            model_name='strategyinputbinding',
            constraint=models.UniqueConstraint(fields=('strategy_version', 'requirement'), name='unique_version_input_requirement'),
        ),
        migrations.RunPython(seed_plugins, migrations.RunPython.noop),
    ]
