# Generated by Django 5.1.7 on 2026-07-11 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
        ('oms', '0001_initial'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionSizingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=128)),
                ('max_loss_fraction', models.DecimalField(decimal_places=10, default='0.005', max_digits=12)),
                ('max_instrument_weight', models.DecimalField(decimal_places=10, default='0.10', max_digits=12)),
                ('max_participation_rate', models.DecimalField(decimal_places=10, default='0.01', max_digits=12)),
                ('max_strategy_exposure', models.DecimalField(decimal_places=10, default='1', max_digits=12)),
                ('max_gross_exposure', models.DecimalField(decimal_places=10, default='1', max_digits=12)),
                ('max_net_exposure', models.DecimalField(decimal_places=10, default='1', max_digits=12)),
                ('minimum_stop_fraction', models.DecimalField(decimal_places=10, default='0.001', max_digits=12)),
                ('calculation_version', models.PositiveIntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sizing_policies', to='portfolios.tradingportfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PositionSizingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('side', models.CharField(max_length=4)),
                ('target_quantity', models.DecimalField(decimal_places=8, max_digits=24)),
                ('risk_quantity', models.DecimalField(decimal_places=8, max_digits=24)),
                ('weight_quantity', models.DecimalField(decimal_places=8, max_digits=24)),
                ('liquidity_quantity', models.DecimalField(decimal_places=8, max_digits=24)),
                ('cash_quantity', models.DecimalField(decimal_places=8, max_digits=24)),
                ('broker_quantity', models.DecimalField(decimal_places=8, max_digits=24)),
                ('approved_quantity', models.DecimalField(decimal_places=8, max_digits=24)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=24)),
                ('stop_price', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('risk_budget', models.DecimalField(decimal_places=8, max_digits=24)),
                ('binding_constraint', models.CharField(max_length=32)),
                ('limits', models.JSONField(default=dict)),
                ('calculation_version', models.PositiveIntegerField(default=1)),
                ('rejected_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instruments.instrument')),
                ('order_intent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sizing_decision', to='oms.orderintent')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='position_sizing.positionsizingpolicy')),
            ],
        ),
    ]
