# Generated by Django 5.1.7 on 2026-07-11 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('asset_class', models.CharField(default='STK', max_length=24)),
                ('exchange', models.CharField(default='SMART', max_length=32)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('sector', models.CharField(blank=True, max_length=64)),
                ('lot_size', models.DecimalField(decimal_places=8, default=1, max_digits=20)),
                ('min_tick', models.DecimalField(decimal_places=8, default='0.01', max_digits=20)),
                ('tradable', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('symbol', 'asset_class', 'exchange', 'currency'), name='unique_instrument')],
            },
        ),
        migrations.CreateModel(
            name='BrokerContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conid', models.BigIntegerField(unique=True)),
                ('primary_exchange', models.CharField(blank=True, max_length=32)),
                ('local_symbol', models.CharField(blank=True, max_length=64)),
                ('qualified_at', models.DateTimeField(blank=True, null=True)),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='broker_contract', to='instruments.instrument')),
            ],
        ),
    ]
