# Generated by Django 5.1.7 on 2026-07-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='fractional_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instrument',
            name='multiplier',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=20),
        ),
        migrations.AddField(
            model_name='instrument',
            name='trading_calendar',
            field=models.CharField(default='XNYS', max_length=64),
        ),
    ]
