# Generated by Django 5.1.7 on 2026-07-11 09:59

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxevent',
            name='available_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='event_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='event_type',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='partition_key',
            field=models.CharField(default='', max_length=128),
        ),
    ]
