# Generated by Django 5.1.7 on 2026-07-14 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0003_exact_contract_identity'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioOptimizationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Markowitz policy', max_length=128)),
                ('method', models.CharField(choices=[('MINIMUM_VARIANCE', 'MINIMUM_VARIANCE'), ('MAXIMUM_SHARPE', 'MAXIMUM_SHARPE')], default='MINIMUM_VARIANCE', max_length=32)),
                ('lookback_days', models.PositiveIntegerField(default=252)),
                ('return_estimation', models.CharField(default='HISTORICAL_MEAN', max_length=32)),
                ('covariance_estimation', models.CharField(default='SAMPLE', max_length=32)),
                ('risk_free_rate', models.DecimalField(decimal_places=8, default='0', max_digits=12)),
                ('target_cash_weight', models.DecimalField(decimal_places=8, default='0.02', max_digits=10)),
                ('minimum_weight', models.DecimalField(decimal_places=8, default='0', max_digits=10)),
                ('maximum_weight', models.DecimalField(decimal_places=8, default='1', max_digits=10)),
                ('maximum_turnover', models.DecimalField(decimal_places=8, default='1', max_digits=10)),
                ('transaction_cost_penalty', models.DecimalField(decimal_places=8, default='0', max_digits=16)),
                ('long_only', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('execution_mode', models.CharField(default='SHADOW', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='optimization_policy', to='portfolios.tradingportfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioUniverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default universe', max_length=128)),
                ('include_strategy_instruments', models.BooleanField(default=False)),
                ('minimum_history_observations', models.PositiveIntegerField(default=60)),
                ('maximum_instruments', models.PositiveIntegerField(default=50)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='optimization_universe', to='portfolios.tradingportfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioOptimizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('trigger', models.CharField(default='MANUAL', max_length=40)),
                ('status', models.CharField(default='CALCULATING', max_length=24)),
                ('input_start_date', models.DateField(blank=True, null=True)),
                ('input_end_date', models.DateField(blank=True, null=True)),
                ('nav', models.DecimalField(decimal_places=8, max_digits=24)),
                ('current_weights', models.JSONField(default=dict)),
                ('expected_returns', models.JSONField(default=dict)),
                ('covariance_snapshot', models.JSONField(default=dict)),
                ('constraints_snapshot', models.JSONField(default=dict)),
                ('policy_snapshot', models.JSONField(default=dict)),
                ('solver_status', models.CharField(blank=True, max_length=64)),
                ('objective_value', models.DecimalField(blank=True, decimal_places=12, max_digits=28, null=True)),
                ('expected_return', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('expected_volatility', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('turnover', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('cash_weight', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('warnings', models.JSONField(default=list)),
                ('error_details', models.JSONField(default=dict)),
                ('flow_reference', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio_optimization.portfoliooptimizationpolicy')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='optimization_runs', to='portfolios.tradingportfolio')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio_optimization.portfoliouniverse')),
            ],
        ),
        migrations.CreateModel(
            name='OptimizedPortfolioTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_weight', models.DecimalField(decimal_places=8, max_digits=12)),
                ('optimized_weight', models.DecimalField(decimal_places=8, max_digits=12)),
                ('weight_change', models.DecimalField(decimal_places=8, max_digits=12)),
                ('target_value', models.DecimalField(decimal_places=8, max_digits=24)),
                ('expected_return_contribution', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('risk_contribution', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('constraint_status', models.CharField(blank=True, max_length=64)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instruments.instrument')),
                ('optimization_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='portfolio_optimization.portfoliooptimizationrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('optimization_run', 'instrument'), name='unique_optimized_run_instrument')],
            },
        ),
        migrations.CreateModel(
            name='PortfolioUniverseInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instruments.instrument')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='portfolio_optimization.portfoliouniverse')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('universe', 'instrument'), name='unique_portfolio_universe_instrument')],
            },
        ),
    ]
