# Generated by Django 5.1.7 on 2026-07-11 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('cash_buffer_pct', models.DecimalField(decimal_places=6, default='0.02', max_digits=8)),
                ('margin_buffer_pct', models.DecimalField(decimal_places=6, default='0.10', max_digits=8)),
                ('minimum_notional', models.DecimalField(decimal_places=8, default='10', max_digits=20)),
                ('minimum_quantity', models.DecimalField(decimal_places=8, default='0.00000001', max_digits=20)),
                ('minimum_drift', models.DecimalField(decimal_places=6, default='0.001', max_digits=8)),
                ('kill_switch', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolios', to='accounts.brokeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='PositionLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delta', models.DecimalField(decimal_places=8, max_digits=24)),
                ('price', models.DecimalField(decimal_places=8, max_digits=24)),
                ('kind', models.CharField(max_length=32)),
                ('reference', models.CharField(max_length=128)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instruments.instrument')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolios.tradingportfolio')),
            ],
        ),
        migrations.CreateModel(
            name='CashLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('currency', models.CharField(max_length=8)),
                ('kind', models.CharField(max_length=32)),
                ('reference', models.CharField(max_length=128)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolios.tradingportfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('average_cost', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('market_price', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instruments.instrument')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='portfolios.tradingportfolio')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('portfolio', 'instrument'), name='unique_portfolio_position')],
            },
        ),
    ]
