# Generated by Django 5.1.7 on 2026-07-15 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allocation', '0009_rebalancerun_rebalance_port_status_idx_and_more'),
        ('instruments', '0003_exact_contract_identity'),
        ('portfolios', '0003_portfolioposition_portfolio_position_time_idx'),
        ('strategies', '0007_strategyallocation_strategy_alloc_priority_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioConstructionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Portfolio Builder', max_length=128)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('ACTIVE', 'ACTIVE'), ('PAUSED', 'PAUSED')], default='DRAFT', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='construction_plan', to='portfolios.tradingportfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioConstructionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('request_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(default='CALCULATING', max_length=24)),
                ('application_status', models.CharField(choices=[('NOT_APPLIED', 'NOT_APPLIED'), ('QUEUED', 'QUEUED'), ('APPLYING', 'APPLYING'), ('APPLIED', 'APPLIED'), ('FAILED', 'FAILED')], default='NOT_APPLIED', max_length=24)),
                ('application_idempotency_key', models.CharField(blank=True, max_length=128)),
                ('retryable', models.BooleanField(default=False)),
                ('last_error', models.CharField(blank=True, max_length=1000)),
                ('attempt_count', models.PositiveIntegerField(default=1)),
                ('nav', models.DecimalField(decimal_places=8, max_digits=24)),
                ('plan_snapshot', models.JSONField(default=dict)),
                ('goal_snapshot', models.JSONField(default=list)),
                ('selection_snapshot', models.JSONField(default=list)),
                ('policy_snapshot', models.JSONField(default=dict)),
                ('goal_results', models.JSONField(default=list)),
                ('final_target_weights', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('warnings', models.JSONField(default=list)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_rebalance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_construction', to='allocation.rebalancerun')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='portfolio_construction.portfolioconstructionplan')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioConstructionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_weight', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('target_weight', models.DecimalField(decimal_places=8, max_digits=12)),
                ('target_value', models.DecimalField(decimal_places=8, max_digits=24)),
                ('expected_return_contribution', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('risk_contribution', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('goal_contributions', models.JSONField(default=list)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('construction_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='portfolio_construction.portfolioconstructionrun')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instruments.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioGoalAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('allocation_weight', models.DecimalField(decimal_places=8, max_digits=10)),
                ('timeframe_bucket', models.CharField(choices=[('NOW', 'Now, up to 30 days'), ('HURRY', 'Hurry, 1-3 months'), ('FAST', 'Fast, 3-12 months'), ('BUILD', 'Build, 1-3 years'), ('GROW', 'Grow, 3-7 years'), ('COMPOUND', 'Compound, 7+ years')], max_length=16)),
                ('risk_level', models.PositiveSmallIntegerField(choices=[(1, 'Capital Preservation'), (2, 'Conservative'), (3, 'Balanced'), (4, 'Growth'), (5, 'Aggressive / High Risk-High Reward')])),
                ('enabled', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='portfolio_construction.portfolioconstructionplan')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GoalStrategySelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_timeframe', models.CharField(max_length=16)),
                ('parameter_overrides', models.JSONField(default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_strategy_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='construction_selections', to='strategies.strategyinstance')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instruments.instrument')),
                ('strategy_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='strategies.strategydefinition')),
                ('goal_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='portfolio_construction.portfoliogoalallocation')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyConstructionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supported_goal_timeframes', models.JSONField(default=list)),
                ('minimum_risk', models.PositiveSmallIntegerField(default=1)),
                ('maximum_risk', models.PositiveSmallIntegerField(default=5)),
                ('construction_enabled', models.BooleanField(default=True)),
                ('user_selectable', models.BooleanField(default=True)),
                ('summary', models.TextField(blank=True)),
                ('limitations', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy_definition', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='construction_profile', to='strategies.strategydefinition')),
            ],
        ),
        migrations.AddIndex(
            model_name='portfolioconstructionrun',
            index=models.Index(fields=['plan', 'status', '-created_at'], name='construction_plan_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='portfolioconstructiontarget',
            constraint=models.UniqueConstraint(fields=('construction_run', 'instrument'), name='unique_construction_run_instrument'),
        ),
        migrations.AddConstraint(
            model_name='portfoliogoalallocation',
            constraint=models.CheckConstraint(condition=models.Q(('allocation_weight__gte', 0), ('allocation_weight__lte', 1)), name='goal_allocation_weight_between_zero_one'),
        ),
        migrations.AddConstraint(
            model_name='portfoliogoalallocation',
            constraint=models.CheckConstraint(condition=models.Q(('risk_level__gte', 1), ('risk_level__lte', 5)), name='goal_risk_level_between_one_five'),
        ),
        migrations.AddConstraint(
            model_name='goalstrategyselection',
            constraint=models.UniqueConstraint(fields=('goal_allocation', 'strategy_definition', 'instrument', 'execution_timeframe'), name='unique_goal_strategy_stock_timeframe'),
        ),
        migrations.AddConstraint(
            model_name='strategyconstructionprofile',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_risk__gte', 1), ('minimum_risk__lte', 5)), name='construction_profile_minimum_risk'),
        ),
        migrations.AddConstraint(
            model_name='strategyconstructionprofile',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_risk__gte', 1), ('maximum_risk__lte', 5)), name='construction_profile_maximum_risk'),
        ),
        migrations.AddConstraint(
            model_name='strategyconstructionprofile',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_risk__lte', models.F('maximum_risk'))), name='construction_profile_risk_order'),
        ),
    ]
