# Generated by Django 5.1.7 on 2026-07-15 07:30

import hashlib
import json
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


def _canonical(value):
    if isinstance(value, dict):
        return {str(key): _canonical(value[key]) for key in sorted(value)}
    if isinstance(value, (list, tuple)):
        return [_canonical(item) for item in value]
    if isinstance(value, bool) or value is None:
        return value
    if isinstance(value, (int, float, Decimal)):
        normalized = format(Decimal(str(value)).normalize(), "f")
        return "0" if normalized in {"-0", ""} else normalized
    return str(value)


def _parameter_hash(parameters):
    body = json.dumps(
        {"operation": "parameters", "payload": _canonical(parameters)},
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    )
    return hashlib.sha256(body.encode()).hexdigest()


def split_legacy_selections(apps, schema_editor):
    LegacySelection = apps.get_model("portfolio_construction", "GoalStrategySelection")
    InstrumentSelection = apps.get_model("portfolio_construction", "GoalInstrumentSelection")
    Assignment = apps.get_model("portfolio_construction", "GoalStrategyAssignment")
    rows = list(LegacySelection.objects.all().order_by("goal_allocation_id", "instrument_id", "id"))
    grouped = {}
    for row in rows:
        grouped.setdefault((row.goal_allocation_id, row.instrument_id), []).append(row)
    for (goal_id, instrument_id), selections in grouped.items():
        instrument_selection = InstrumentSelection.objects.create(
            goal_allocation_id=goal_id,
            instrument_id=instrument_id,
            enabled=any(row.enabled for row in selections),
            display_order=0,
        )
        enabled_count = sum(1 for row in selections if row.enabled)
        for row in selections:
            share = Decimal(1) / Decimal(enabled_count) if row.enabled and enabled_count else Decimal(0)
            assignment = Assignment.objects.create(
                goal_instrument_selection_id=instrument_selection.pk,
                strategy_definition_id=row.strategy_definition_id,
                execution_timeframe=row.execution_timeframe,
                parameter_overrides=row.parameter_overrides,
                parameter_hash=_parameter_hash(row.parameter_overrides),
                strategy_share=share,
                create_instance=True,
                enabled=row.enabled,
                created_strategy_instance_id=row.created_strategy_instance_id,
            )
            Assignment.objects.filter(pk=assignment.pk).update(
                created_at=row.created_at,
                updated_at=row.updated_at,
            )
        InstrumentSelection.objects.filter(pk=instrument_selection.pk).update(
            created_at=min(row.created_at for row in selections),
            updated_at=max(row.updated_at for row in selections),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_exact_contract_identity'),
        ('portfolio_construction', '0002_seed_strategy_construction_profiles'),
        ('strategies', '0007_strategyallocation_strategy_alloc_priority_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioconstructionrun',
            old_name='selection_snapshot',
            new_name='assignment_snapshot',
        ),
        migrations.AddField(
            model_name='portfolioconstructionrun',
            name='instrument_snapshot',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='GoalInstrumentSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('minimum_weight', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('maximum_weight', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_selections', to='portfolio_construction.portfoliogoalallocation')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instruments.instrument')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GoalStrategyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_timeframe', models.CharField(max_length=16)),
                ('parameter_overrides', models.JSONField(default=dict)),
                ('parameter_hash', models.CharField(max_length=64)),
                ('strategy_share', models.DecimalField(decimal_places=8, default=1, max_digits=10)),
                ('create_instance', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_strategy_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='construction_assignments', to='strategies.strategyinstance')),
                ('goal_instrument_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='portfolio_construction.goalinstrumentselection')),
                ('order_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='strategies.orderpolicy')),
                ('risk_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='strategies.strategyriskpolicy')),
                ('strategy_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='strategies.strategydefinition')),
            ],
        ),
        migrations.RunPython(split_legacy_selections, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='GoalStrategySelection',
        ),
        migrations.AddConstraint(
            model_name='goalinstrumentselection',
            constraint=models.UniqueConstraint(fields=('goal_allocation', 'instrument'), name='unique_goal_instrument_selection'),
        ),
        migrations.AddConstraint(
            model_name='goalinstrumentselection',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_weight__isnull', True), models.Q(('minimum_weight__gte', 0), ('minimum_weight__lte', 1)), _connector='OR'), name='goal_instrument_minimum_weight_range'),
        ),
        migrations.AddConstraint(
            model_name='goalinstrumentselection',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_weight__isnull', True), models.Q(('maximum_weight__gte', 0), ('maximum_weight__lte', 1)), _connector='OR'), name='goal_instrument_maximum_weight_range'),
        ),
        migrations.AddConstraint(
            model_name='goalinstrumentselection',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_weight__isnull', True), ('maximum_weight__isnull', True), ('minimum_weight__lte', models.F('maximum_weight')), _connector='OR'), name='goal_instrument_weight_order'),
        ),
        migrations.AddConstraint(
            model_name='goalstrategyassignment',
            constraint=models.UniqueConstraint(fields=('goal_instrument_selection', 'strategy_definition', 'execution_timeframe', 'parameter_hash'), name='unique_goal_strategy_assignment_identity'),
        ),
        migrations.AddConstraint(
            model_name='goalstrategyassignment',
            constraint=models.CheckConstraint(condition=models.Q(('strategy_share__gte', 0), ('strategy_share__lte', 1)), name='goal_strategy_share_between_zero_one'),
        ),
    ]
