# Generated by Django 5.1.7 on 2026-07-20 05:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('broker_gateway', '0002_brokerpositionsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerGatewaySessionSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_username', models.TextField()),
                ('encrypted_password', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BrokerSessionAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_alias', models.CharField(blank=True, max_length=128)),
                ('available', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='brokersynccursor',
            name='name',
            field=models.CharField(default='gateway-events', max_length=64),
        ),
        migrations.CreateModel(
            name='BrokerGatewaySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=128)),
                ('username_hint', models.CharField(max_length=128)),
                ('mode', models.CharField(choices=[('paper', 'Paper'), ('live', 'Live')], max_length=8)),
                ('status', models.CharField(choices=[('CREATING', 'Creating'), ('STARTING', 'Starting'), ('WAITING_FOR_LOGIN', 'Waiting for login'), ('WAITING_FOR_2FA', 'Waiting for 2FA'), ('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('LOGIN_FAILED', 'Login failed'), ('ERROR', 'Error'), ('STOPPING', 'Stopping'), ('DELETED', 'Deleted')], default='CREATING', max_length=32)),
                ('child_container_id', models.CharField(blank=True, max_length=160)),
                ('child_container_name', models.CharField(max_length=128, unique=True)),
                ('internal_base_url', models.URLField(blank=True, max_length=255)),
                ('encrypted_gateway_token', models.TextField()),
                ('encrypted_novnc_password', models.TextField()),
                ('commands_enabled', models.BooleanField(default=False)),
                ('last_gateway_state', models.JSONField(blank=True, default=dict)),
                ('last_qch_state', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('lifecycle_version', models.PositiveBigIntegerField(default=1)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'deleted_at'], name='broker_session_status_idx'), models.Index(fields=['mode', 'created_at'], name='broker_session_mode_idx')],
            },
        ),
        migrations.AddField(
            model_name='brokerpositionsnapshot',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='position_snapshots', to='broker_gateway.brokergatewaysession'),
        ),
        migrations.AddField(
            model_name='brokersynccursor',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sync_cursors', to='broker_gateway.brokergatewaysession'),
        ),
        migrations.AddConstraint(
            model_name='brokersynccursor',
            constraint=models.UniqueConstraint(fields=('session', 'name'), name='unique_session_sync_cursor'),
        ),
        migrations.AddField(
            model_name='brokergatewaysessionsecret',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_secret', to='broker_gateway.brokergatewaysession'),
        ),
        migrations.AddField(
            model_name='brokersessionaccount',
            name='broker_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gateway_sessions', to='accounts.brokeraccount'),
        ),
        migrations.AddField(
            model_name='brokersessionaccount',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_accounts', to='broker_gateway.brokergatewaysession'),
        ),
        migrations.AddIndex(
            model_name='brokergatewaysessionsecret',
            index=models.Index(fields=['expires_at'], name='broker_secret_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='brokersessionaccount',
            index=models.Index(fields=['session', 'available'], name='broker_session_account_idx'),
        ),
        migrations.AddConstraint(
            model_name='brokersessionaccount',
            constraint=models.UniqueConstraint(fields=('session', 'broker_account'), name='unique_session_broker_account'),
        ),
    ]
