# Generated by Django 5.1.7 on 2026-07-11 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allocation', '0001_initial'),
        ('instruments', '0001_initial'),
        ('portfolios', '0001_initial'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=4)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=24)),
                ('order_type', models.CharField(default='MKT', max_length=16)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('stop_price', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('reference_price', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('time_in_force', models.CharField(default='DAY', max_length=8)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('source', models.CharField(default='MANUAL', max_length=32)),
                ('mode', models.CharField(default='PAPER', max_length=16)),
                ('requires_fresh_price', models.BooleanField(default=False)),
                ('execution_priority', models.PositiveIntegerField(default=100)),
                ('eligible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instruments.instrument')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolios.tradingportfolio')),
                ('rebalance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='allocation.rebalancerun')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='strategies.tradingstrategy')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(max_length=64, unique=True)),
                ('broker_order_id', models.CharField(blank=True, max_length=64)),
                ('broker_permanent_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('RISK_APPROVED', 'RISK_APPROVED'), ('QUEUED', 'QUEUED'), ('BROKER_BLOCKED', 'BROKER_BLOCKED'), ('SUBMITTED', 'SUBMITTED'), ('ACKNOWLEDGED', 'ACKNOWLEDGED'), ('PARTIALLY_FILLED', 'PARTIALLY_FILLED'), ('FILLED', 'FILLED'), ('CANCEL_PENDING', 'CANCEL_PENDING'), ('CANCELLED', 'CANCELLED'), ('REJECTED', 'REJECTED'), ('EXPIRED', 'EXPIRED'), ('UNKNOWN', 'UNKNOWN')], default='CREATED', max_length=24)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=24)),
                ('filled_quantity', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('average_fill_price', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='oms.orderintent')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(max_length=24)),
                ('source', models.CharField(max_length=32)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('event_key', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='oms.order')),
            ],
        ),
    ]
