# Generated by Django 5.1.7 on 2026-07-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0002_orderintent_strategy_instance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderintent',
            name='strategy_version_snapshot',
            field=models.JSONField(default=list),
        ),
    ]
