# Generated by Django 5.1.7 on 2026-07-14 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0004_orderstatushistory_broker_diagnostics'),
        ('strategies', '0003_warmup_runtime_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderintent',
            name='strategy_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='orderintent',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategies.tradingstrategy'),
        ),
        migrations.AlterField(
            model_name='orderintent',
            name='strategy_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategies.strategyinstance'),
        ),
        migrations.AlterField(
            model_name='orderintent',
            name='strategy_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategies.strategyversion'),
        ),
    ]
