# Generated by Django 5.1.7 on 2026-07-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=64, unique=True)),
                ('alias', models.CharField(blank=True, max_length=128)),
                ('base_currency', models.CharField(default='USD', max_length=8)),
                ('net_liquidation', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('available_cash', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('buying_power', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('daily_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('kill_switch', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
