# Generated by Django 5.1.7 on 2026-07-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_exact_contract_identity'),
        ('portfolios', '0002_position_realized_pnl'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='portfolioposition',
            index=models.Index(fields=['portfolio', 'updated_at'], name='portfolio_position_time_idx'),
        ),
    ]
