# Generated by Django 5.1.7 on 2026-07-20 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_gateway', '0003_brokergatewaysessionsecret_brokersessionaccount_and_more'),
        ('portfolios', '0003_portfolioposition_portfolio_position_time_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingportfolio',
            name='gateway_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portfolios', to='broker_gateway.brokergatewaysession'),
        ),
    ]
