# Generated by Django 5.1.7 on 2026-07-14 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0003_exact_contract_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketDataProviderConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='FINNHUB', max_length=32, unique=True)),
                ('encrypted_api_key', models.TextField(blank=True)),
                ('api_key_last_four', models.CharField(blank=True, max_length=4)),
                ('override_environment', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('rate_limit_state', models.JSONField(default=dict)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketDataFetchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='FINNHUB', max_length=32)),
                ('purpose', models.CharField(default='HISTORY', max_length=32)),
                ('status', models.CharField(default='STARTED', max_length=24)),
                ('requested_start', models.DateField(blank=True, null=True)),
                ('requested_end', models.DateField(blank=True, null=True)),
                ('records_received', models.PositiveIntegerField(default=0)),
                ('records_written', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_date', models.DateField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=24)),
                ('high', models.DecimalField(decimal_places=8, max_digits=24)),
                ('low', models.DecimalField(decimal_places=8, max_digits=24)),
                ('close', models.DecimalField(decimal_places=8, max_digits=24)),
                ('adjusted_close', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('volume', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('provider', models.CharField(default='FINNHUB', max_length=32)),
                ('data_version', models.PositiveIntegerField(default=1)),
                ('quality_status', models.CharField(default='COMPLETE', max_length=24)),
                ('fetched_at', models.DateTimeField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_history', to='instruments.instrument')),
            ],
            options={
                'ordering': ['trading_date'],
                'indexes': [models.Index(fields=['instrument', 'provider', 'trading_date'], name='market_data_instrum_b14309_idx')],
                'constraints': [models.UniqueConstraint(fields=('instrument', 'trading_date', 'provider'), name='unique_instrument_daily_price_provider')],
            },
        ),
    ]
