# Generated by Django 5.1.7 on 2026-07-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_marketdatafetchrun_response_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketdataproviderconfiguration',
            name='last_test_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
