# Generated by Django 5.1.7 on 2026-07-11 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(max_length=40)),
                ('status', models.CharField(default='RUNNING', max_length=24)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32)),
                ('severity', models.CharField(max_length=16)),
                ('internal_value', models.JSONField(default=dict)),
                ('broker_value', models.JSONField(default=dict)),
                ('material', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breaks', to='reconciliation.reconciliationrun')),
            ],
        ),
    ]
