# Generated by Django 5.1.7 on 2026-07-20 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_gateway', '0003_brokergatewaysessionsecret_brokersessionaccount_and_more'),
        ('reconciliation', '0002_account_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationrun',
            name='gateway_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_runs', to='broker_gateway.brokergatewaysession'),
        ),
    ]
