import {useEffect,useMemo,useState} from 'react'
import {Activity,BookOpen,ChartCandlestick,ChevronRight,CircleDollarSign,FileClock,Gauge,Landmark,LayoutDashboard,RefreshCw,ShieldAlert,Terminal,Unplug,Zap} from 'lucide-react'
import {api} from './api'
import {ExposureChart} from './ExposureChart'
import {useTerminalStore} from './store'

const pages=[['Overview',LayoutDashboard],['Gateway',Unplug],['Accounts',Landmark],['Portfolio',BookOpen],['Strategies',ChartCandlestick],['Orders',FileClock],['Executions',CircleDollarSign],['Reconciliation',RefreshCw],['Risk',ShieldAlert],['System Logs',Terminal]] as const
const fmt=(x:any)=>x===null||x===undefined?'—':String(x)
function Status({value}:{value:string}){const v=(value||'UNKNOWN').toUpperCase();const tone=/LIVE|CONNECTED|APPROVED|FILLED|HEALTHY|PAPER/.test(v)?'good':/BLOCK|REJECT|KILL|ERROR|DISCONNECT/.test(v)?'bad':'warn';return <span className={`status ${tone}`}><i/>{v}</span>}
function Panel({title,children,actions}:{title:string;children:React.ReactNode;actions?:React.ReactNode}){return <section className="panel"><header><span>{title}</span>{actions}</header><div className="panel-body">{children}</div></section>}
function Table({rows,columns}:{rows:any[];columns:string[]}){return <div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{c.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={r.id||i}>{columns.map(c=><td key={c} className={/id|price|quantity|cash|power|pnl|status|weight|commission/.test(c)?'mono':''}>{c==='status'?<Status value={fmt(r[c])}/>:fmt(r[c])}</td>)}</tr>):<tr><td colSpan={columns.length} className="empty">NO RECORDS</td></tr>}</tbody></table></div>}
function Overview(){const s=useTerminalStore();const account=s.accounts[0]||{};return <div className="grid"><Panel title="OPERATING STATE"><div className="metrics"><Metric label="MODE" value={s.system?.mode||'PAPER'} status/><Metric label="GATEWAY" value={s.gateway?.connected?'CONNECTED':'DISCONNECTED'} status/><Metric label="SYNC" value={s.gateway?.reconciled?'RECONCILED':'BLOCKED'} status/><Metric label="BREAKS" value={s.system?.material_breaks||0}/></div></Panel><Panel title="ACCOUNT SUMMARY"><div className="metrics"><Metric label="NAV" value={account.net_liquidation}/><Metric label="CASH" value={account.available_cash}/><Metric label="BUYING POWER" value={account.buying_power}/><Metric label="DAILY P&L" value={account.daily_pnl}/></div></Panel><Panel title="PORTFOLIO TRACE"><ExposureChart/></Panel><Panel title="ACTIVITY"><div className="metrics"><Metric label="OPEN ORDERS" value={s.orders.filter(x=>!['FILLED','CANCELLED','REJECTED'].includes(x.status)).length}/><Metric label="EXECUTIONS" value={s.executions.length}/><Metric label="POSITIONS" value={s.positions.length}/><Metric label="RISK BLOCKS" value={(s.risk?.decisions||[]).filter((x:any)=>x.decision!=='APPROVED').length}/></div></Panel></div>}
function Metric({label,value,status}:{label:string;value:any;status?:boolean}){return <div className="metric"><small>{label}</small><strong className="mono">{status?<Status value={fmt(value)}/>:fmt(value)}</strong></div>}
function Gateway(){const s=useTerminalStore();const reconnect=()=>api('gateway/',{method:'POST'}).then(s.refresh);const gateway=(import.meta.env.VITE_GATEWAY_PUBLIC_URL||'http://localhost:8080').replace(/\/$/,'');return <div className="grid"><Panel title="BROKER SESSION" actions={<button onClick={reconnect}><RefreshCw/>RECONNECT</button>}><div className="metrics"><Metric label="STATE" value={s.gateway?.connected?'CONNECTED':'DISCONNECTED'} status/><Metric label="MODE" value={s.gateway?.mode||'PAPER'} status/><Metric label="BROKER SYNC" value={s.gateway?.reconciled?'RECONCILED':'RECONCILING'} status/><Metric label="LAST CALLBACK" value={s.gateway?.last_callback}/></div></Panel><Panel title="OPERATOR CONSOLE"><p>Use noVNC only for IBKR authentication, 2FA, and Gateway settings.</p><a className="button" href={`${gateway}/novnc/vnc.html`} target="_blank" rel="noreferrer">OPEN noVNC <ChevronRight/></a></Panel></div>}
function Accounts(){const s=useTerminalStore();return <Panel title="BROKER ACCOUNTS"><Table rows={s.accounts} columns={['account_id','base_currency','net_liquidation','available_cash','buying_power','daily_pnl','is_reconciled']}/></Panel>}
function Portfolio(){const s=useTerminalStore();return <Panel title="IBKR POSITIONS"><Table rows={s.positions} columns={['account_id','symbol','asset_class','quantity','average_cost','market_price','market_value','currency','updated_at']}/></Panel>}
function Strategies(){const s=useTerminalStore();const run=(id:number)=>api('strategy-runs/',{method:'POST',body:JSON.stringify({strategy_id:id})}).then(s.refresh);return <Panel title="DETERMINISTIC STRATEGIES"><Table rows={s.strategies.map(x=>({...x,action:<button onClick={()=>run(x.id)}>RUN</button>}))} columns={['name','strategy_type','version','enabled','schedule','allocated_capital','maximum_target_weight']}/><div className="strategy-actions">{s.strategies.map(x=><button key={x.id} onClick={()=>run(x.id)} disabled={!x.enabled}><Zap/>RUN {x.name}</button>)}</div></Panel>}
function Orders(){const s=useTerminalStore();const [message,setMessage]=useState('');const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const quantity=Number(f.get('quantity'));if(quantity<=0){setMessage('Quantity must be greater than zero');return}setMessage('VALIDATED — RUNNING PRE-TRADE RISK');try{const result:any=await api('orders/',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({portfolio_id:Number(f.get('portfolio_id')),instrument_id:Number(f.get('instrument_id')),side:f.get('side'),order_type:f.get('order_type'),quantity:f.get('quantity'),reference_price:f.get('reference_price'),time_in_force:f.get('time_in_force')})});setMessage(`${result.decision||'ACCEPTED'} — ${result.internal_id}`);await s.refresh()}catch(error){setMessage(`BLOCKED — ${(error as Error).message}`)}};const cancel=async(id:string)=>{await api(`orders/${id}/cancel/`,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:'{}'});await s.refresh()};const modify=async(id:string,current:any)=>{const quantity=window.prompt('New total quantity',String(current));if(!quantity)return;await api(`orders/${id}/`,{method:'PATCH',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({quantity})});await s.refresh()};const active=s.orders.filter(x=>['QUEUED','SUBMITTED','ACKNOWLEDGED','PARTIALLY_FILLED'].includes(x.status));return <div className="grid"><Panel title="ORDER TICKET // PRE-TRADE RISK"><form onSubmit={submit} className="ticket"><label>PORTFOLIO<select name="portfolio_id" required>{s.portfolios.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>INSTRUMENT<select name="instrument_id" required>{s.instruments.map(x=><option key={x.id} value={x.id}>{x.symbol} / {x.exchange}</option>)}</select></label><label>SIDE<select name="side"><option>BUY</option><option>SELL</option></select></label><label>TYPE<select name="order_type"><option>MKT</option><option>LMT</option><option>STP</option><option>STP_LMT</option></select></label><label>QUANTITY<input name="quantity" type="number" min="0" step="any" required/></label><label>REFERENCE PRICE<input name="reference_price" type="number" min="0" step="any" required/></label><label>TIF<select name="time_in_force"><option>DAY</option><option>GTC</option></select></label><button type="submit">SUBMIT TO RISK</button><output>{message}</output></form></Panel><Panel title="IBKR ORDER BLOTTER"><Table rows={s.orders} columns={['account_id','symbol','side','order_type','status','quantity','filled_quantity','average_fill_price','broker_order_id','internal_id','updated_at']}/><div className="strategy-actions">{active.map(x=><span key={x.internal_id}><button onClick={()=>modify(x.internal_id,x.quantity)}>MODIFY {x.internal_id.slice(0,8)}</button><button className="danger" onClick={()=>cancel(x.internal_id)}>CANCEL</button></span>)}</div></Panel></div>}
function Executions(){const s=useTerminalStore();return <Panel title="IBKR EXECUTION LEDGER"><Table rows={s.executions} columns={['account_id','symbol','execution_id','order_id','quantity','price','commission','currency','executed_at']}/></Panel>}
function Reconciliation(){const s=useTerminalStore();return <div className="grid"><Panel title="RECONCILIATION RUNS"><Table rows={s.reconciliation?.runs||[]} columns={['trigger','status','started_at','completed_at']}/></Panel><Panel title="UNRESOLVED BREAKS"><Table rows={s.reconciliation?.breaks||[]} columns={['category','severity','material','resolved','created_at']}/></Panel></div>}
function Risk(){const s=useTerminalStore();const [confirm,setConfirm]=useState(false);const kill=()=>api('risk/',{method:'POST',body:JSON.stringify({scope:'GLOBAL',enabled:true,reason:'Frontend operator action'})}).then(()=>{setConfirm(false);s.refresh()});return <div className="grid"><Panel title="KILL SWITCHES" actions={<button className="danger" onClick={()=>setConfirm(true)}><ShieldAlert/>ENGAGE GLOBAL</button>}><Table rows={s.risk?.kill_switches||[]} columns={['scope','scope_id','enabled','reason','updated_at']}/>{confirm&&<div className="confirm"><strong>CONFIRM GLOBAL TRADING HALT</strong><button className="danger" onClick={kill}>CONFIRM KILL SWITCH</button><button onClick={()=>setConfirm(false)}>CANCEL</button></div>}</Panel><Panel title="RISK DECISIONS"><Table rows={s.risk?.decisions||[]} columns={['check_name','decision','reason','requested_quantity','approved_quantity','created_at']}/></Panel></div>}
function Logs(){const s=useTerminalStore();return <Panel title="SYSTEM / AUDIT LOG"><Table rows={s.logs} columns={['created_at','event_type','actor','aggregate_type','aggregate_id']}/></Panel>}
const screens:Record<string,()=>JSX.Element>={'Overview':Overview,'Gateway':Gateway,'Accounts':Accounts,'Portfolio':Portfolio,'Strategies':Strategies,'Orders':Orders,'Executions':Executions,'Reconciliation':Reconciliation,'Risk':Risk,'System Logs':Logs}
export default function App(){const [page,setPage]=useState('Overview');const s=useTerminalStore();useEffect(()=>{s.refresh();const id=setInterval(s.refresh,15000);return()=>clearInterval(id)},[]);const Screen=useMemo(()=>screens[page],[page]);return <div className="shell"><aside><div className="brand"><Gauge/><div><b>FINFLOCK</b><span>EXECUTION ENGINE</span></div></div><nav aria-label="Trading sections">{pages.map(([name,Icon])=><button key={name} className={page===name?'active':''} onClick={()=>setPage(name)}><Icon/>{name}<ChevronRight/></button>)}</nav><div className="sidebar-foot"><Status value={s.system?.mode||'PAPER'}/><span>NO DIRECT TWS ACCESS</span></div></aside><main><div className="topbar"><div><small>TRADING /</small><h1>{page}</h1></div><div className="top-state"><Activity/><span>API</span><Status value={s.error?'DEGRADED':'HEALTHY'}/><button aria-label="Refresh data" onClick={s.refresh}><RefreshCw className={s.loading?'spin':''}/></button></div></div>{s.error&&<div className="alert">DATA CHANNEL DEGRADED — {s.error}</div>}<Screen/></main></div>}
