# Generated by Django 5.1.7 on 2026-07-11 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_nav_before', models.DecimalField(decimal_places=8, max_digits=24)),
                ('portfolio_cash_before', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('approved_amount', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('unallocated_amount', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('liquidation_policy', models.CharField(choices=[('PROPORTIONAL', 'PROPORTIONAL'), ('LOWEST_CONVICTION_FIRST', 'LOWEST_CONVICTION_FIRST'), ('MOST_LIQUID_FIRST', 'MOST_LIQUID_FIRST'), ('LOWEST_COST_FIRST', 'LOWEST_COST_FIRST'), ('PRIORITY_ORDER', 'PRIORITY_ORDER')], default='PROPORTIONAL', max_length=40)),
                ('status', models.CharField(default='CALCULATING', max_length=24)),
                ('calculation_version', models.PositiveIntegerField(default=1)),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderIntentAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_delta', models.DecimalField(decimal_places=8, max_digits=24)),
                ('allocated_quantity', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('allocated_value', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('allocated_cost', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('realized_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('method', models.CharField(default='PRO_RATA_TARGET_DELTA', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type', models.CharField(choices=[('DEPOSIT', 'DEPOSIT'), ('WITHDRAWAL', 'WITHDRAWAL'), ('INTERNAL_TRANSFER_IN', 'INTERNAL_TRANSFER_IN'), ('INTERNAL_TRANSFER_OUT', 'INTERNAL_TRANSFER_OUT')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('effective_at', models.DateTimeField()),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(default='REQUESTED', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RebalancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_drift_threshold', models.DecimalField(decimal_places=8, default='0.01', max_digits=10)),
                ('portfolio_drift_threshold', models.DecimalField(decimal_places=8, default='0.05', max_digits=10)),
                ('minimum_trade_notional', models.DecimalField(decimal_places=8, default='10', max_digits=24)),
                ('minimum_trade_quantity', models.DecimalField(decimal_places=8, default='0.00000001', max_digits=24)),
                ('cash_buffer_percent', models.DecimalField(decimal_places=8, default='0.02', max_digits=10)),
                ('fee_buffer', models.DecimalField(decimal_places=8, default='1', max_digits=24)),
                ('maximum_turnover', models.DecimalField(decimal_places=8, default='0.25', max_digits=10)),
                ('sell_before_buy', models.BooleanField(default=True)),
                ('price_staleness_limit', models.PositiveIntegerField(default=300)),
                ('partial_fill_threshold', models.DecimalField(decimal_places=6, default='0.95', max_digits=8)),
                ('mode', models.CharField(default='SHADOW', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RebalanceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(max_length=40)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(default='CALCULATING', max_length=24)),
                ('phase', models.CharField(default='PLANNING', max_length=24)),
                ('mode', models.CharField(default='SHADOW', max_length=16)),
                ('nav', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('snapshot', models.JSONField(default=dict)),
                ('total_drift', models.DecimalField(decimal_places=10, default=0, max_digits=18)),
                ('planned_turnover', models.DecimalField(decimal_places=10, default=0, max_digits=18)),
                ('last_recalculated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StrategyCapitalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital_before', models.DecimalField(decimal_places=8, max_digits=24)),
                ('target_capital', models.DecimalField(decimal_places=8, max_digits=24)),
                ('deficit', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('surplus', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('idle_cash', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
            ],
        ),
        migrations.CreateModel(
            name='TargetPortfolioPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_weight', models.DecimalField(decimal_places=8, max_digits=12)),
                ('target_quantity', models.DecimalField(decimal_places=8, max_digits=24)),
                ('trade_quantity', models.DecimalField(decimal_places=8, max_digits=24)),
                ('reference_price', models.DecimalField(decimal_places=8, max_digits=24)),
                ('current_quantity', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('current_weight', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('drift', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('lot_size', models.DecimalField(decimal_places=8, default=1, max_digits=24)),
                ('estimated_cost', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('suppressed', models.BooleanField(default=False)),
                ('suppression_reason', models.CharField(blank=True, max_length=128)),
                ('rank', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AllocationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=40)),
                ('requested_amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('approved_amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('binding_constraint', models.CharField(blank=True, max_length=64)),
                ('liquidation_required', models.BooleanField(default=False)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(default=dict)),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='strategies.tradingstrategy')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='allocation.allocationrun')),
            ],
        ),
    ]
