# Generated by Django 5.1.7 on 2026-07-13 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0002_initial'),
        ('strategies', '0002_orderpolicy_strategydefinition_strategyriskpolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderintentattribution',
            name='strategy_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='strategies.strategyinstance'),
        ),
        migrations.AddField(
            model_name='orderintentattribution',
            name='strategy_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='strategies.strategyversion'),
        ),
    ]
