# Generated by Django 5.1.7 on 2026-07-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0003_orderintentattribution_strategy_instance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationrun',
            name='allocation_mode',
            field=models.CharField(default='STRATEGY_ALLOCATION', max_length=40),
        ),
    ]
