# Generated by Django 5.1.7 on 2026-07-14 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0004_allocationrun_allocation_mode'),
        ('portfolio_optimization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationrun',
            name='optimization_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portfolio_optimization.portfoliooptimizationrun'),
        ),
        migrations.AddField(
            model_name='rebalancerun',
            name='optimization_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rebalances', to='portfolio_optimization.portfoliooptimizationrun'),
        ),
        migrations.AddField(
            model_name='rebalancerun',
            name='target_source',
            field=models.CharField(default='STRATEGY_AGGREGATION', max_length=40),
        ),
    ]
