# Generated by Django 5.1.7 on 2026-07-15 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0009_rebalancerun_rebalance_port_status_idx_and_more'),
        ('portfolio_construction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebalancerun',
            name='construction_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rebalances', to='portfolio_construction.portfolioconstructionrun'),
        ),
    ]
