# Generated by Django 5.1.7 on 2026-07-11 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentMarketState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FRESH', 'FRESH'), ('STALE', 'STALE'), ('UNAVAILABLE', 'UNAVAILABLE')], default='UNAVAILABLE', max_length=16)),
                ('reference_price', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('latest_event_at', models.DateTimeField(blank=True, null=True)),
                ('watermark_at', models.DateTimeField(blank=True, null=True)),
                ('stale_after_seconds', models.PositiveIntegerField(default=300)),
                ('source_event_id', models.UUIDField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='market_state', to='instruments.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='MarketBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_id', models.CharField(max_length=160)),
                ('interval', models.CharField(max_length=16)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=24)),
                ('high', models.DecimalField(decimal_places=8, max_digits=24)),
                ('low', models.DecimalField(decimal_places=8, max_digits=24)),
                ('close', models.DecimalField(decimal_places=8, max_digits=24)),
                ('volume', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_final', models.BooleanField(default=False)),
                ('source_event_count', models.PositiveIntegerField(default=0)),
                ('produced_at', models.DateTimeField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stream_bars', to='instruments.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=64)),
                ('value', models.DecimalField(blank=True, decimal_places=10, max_digits=28, null=True)),
                ('parameters', models.JSONField(default=dict)),
                ('parameter_version', models.PositiveIntegerField(default=1)),
                ('event_time', models.DateTimeField()),
                ('source_key', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='instruments.instrument')),
                ('bar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='market_streams.marketbar')),
            ],
        ),
        migrations.AddConstraint(
            model_name='marketbar',
            constraint=models.UniqueConstraint(fields=('bar_id', 'version'), name='unique_market_bar_version'),
        ),
        migrations.AddConstraint(
            model_name='indicatorvalue',
            constraint=models.UniqueConstraint(fields=('source_key', 'parameter_version'), name='unique_indicator_source_version'),
        ),
    ]
