# Generated by Django 5.1.7 on 2026-07-15 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_exact_contract_identity'),
        ('market_streams', '0003_market_data_subscription'),
        ('strategies', '0006_remove_legacy_strategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyEvaluationReadiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_input_count', models.PositiveIntegerField(default=0)),
                ('received_input_hashes', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('EVALUATING', 'EVALUATING'), ('COMPLETED', 'COMPLETED'), ('ERROR', 'ERROR')], default='PENDING', max_length=16)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='indicatorvalue',
            index=models.Index(fields=['instrument', 'timeframe', 'is_final', '-event_time'], name='indicator_latest_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorvalue',
            index=models.Index(fields=['source_bar_id', 'source_bar_version', 'parameters_hash', 'is_final'], name='indicator_ready_idx'),
        ),
        migrations.AddIndex(
            model_name='marketbar',
            index=models.Index(fields=['instrument', 'interval', 'is_final', '-window_end'], name='market_bar_latest_idx'),
        ),
        migrations.AddIndex(
            model_name='marketdatasubscription',
            index=models.Index(fields=['state', 'updated_at'], name='market_sub_state_idx'),
        ),
        migrations.AddField(
            model_name='strategyevaluationreadiness',
            name='bar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_readiness', to='market_streams.marketbar'),
        ),
        migrations.AddField(
            model_name='strategyevaluationreadiness',
            name='strategy_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_readiness', to='strategies.strategyinstance'),
        ),
        migrations.AddField(
            model_name='strategyevaluationreadiness',
            name='strategy_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategies.strategyrun'),
        ),
        migrations.AddField(
            model_name='strategyevaluationreadiness',
            name='strategy_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.strategyversion'),
        ),
        migrations.AddIndex(
            model_name='strategyevaluationreadiness',
            index=models.Index(fields=['status', 'updated_at'], name='strategy_ready_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='strategyevaluationreadiness',
            constraint=models.UniqueConstraint(fields=('strategy_instance', 'strategy_version', 'bar'), name='unique_strategy_bar_readiness'),
        ),
    ]
