# Generated by Django 5.1.7 on 2026-07-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('actor', models.CharField(max_length=128)),
                ('aggregate_type', models.CharField(max_length=64)),
                ('aggregate_id', models.CharField(max_length=128)),
                ('data', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(editable=False, unique=True)),
                ('topic', models.CharField(max_length=128)),
                ('partition_key', models.CharField(max_length=128)),
                ('event_type', models.CharField(max_length=128)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('aggregate_type', models.CharField(default='system', max_length=64)),
                ('aggregate_id', models.CharField(max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('causation_id', models.UUIDField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PUBLISHING', 'PUBLISHING'), ('PUBLISHED', 'PUBLISHED'), ('FAILED', 'FAILED')], default='PENDING', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
