# Generated by Django 5.1.7 on 2026-07-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_operationattempt'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['aggregate_type', 'aggregate_id', '-created_at'], name='audit_aggregate_time_idx'),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['status', 'available_at', 'created_at'], name='outbox_publish_queue_idx'),
        ),
    ]
