# Generated by Django 5.1.7 on 2026-07-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_streams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorvalue',
            name='is_final',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='parameters_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='previous_value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=28, null=True),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='source_bar_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='source_bar_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='timeframe',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
