# Generated by Django 5.1.7 on 2026-07-20 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_gateway', '0003_brokergatewaysessionsecret_brokersessionaccount_and_more'),
        ('instruments', '0006_alter_issuer_founded'),
        ('market_streams', '0005_provider_fallback_state'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='marketdatasubscription',
            name='unique_market_data_subscription',
        ),
        migrations.AddField(
            model_name='marketdatasubscription',
            name='gateway_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='market_subscriptions', to='broker_gateway.brokergatewaysession'),
        ),
        migrations.AddConstraint(
            model_name='marketdatasubscription',
            constraint=models.UniqueConstraint(fields=('gateway_session', 'instrument', 'timeframe'), name='unique_session_market_subscription'),
        ),
    ]
