# Generated by Django 5.1.7 on 2026-07-23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_streams", "0006_remove_marketdatasubscription_unique_market_data_subscription_and_more"),
        ("strategies", "0007_strategyallocation_strategy_alloc_priority_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategyEvaluationJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("market_bar_id", models.CharField(max_length=160)),
                ("bar_version", models.PositiveIntegerField()),
                ("event_id", models.CharField(max_length=160)),
                ("event_time", models.DateTimeField()),
                ("source_data_version", models.PositiveIntegerField(default=1)),
                ("expected_input_identity_hashes", models.JSONField(default=list)),
                ("status", models.CharField(choices=[
                    ("WAITING_FOR_INPUT", "WAITING_FOR_INPUT"),
                    ("PENDING", "PENDING"),
                    ("CLAIMED", "CLAIMED"),
                    ("RUNNING", "RUNNING"),
                    ("RETRY", "RETRY"),
                    ("COMPLETED", "COMPLETED"),
                    ("FAILED", "FAILED"),
                ], default="WAITING_FOR_INPUT", max_length=24)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, choices=[
                    ("INFRASTRUCTURE_RETRYABLE", "INFRASTRUCTURE_RETRYABLE"),
                    ("MISSING_INPUT", "MISSING_INPUT"),
                    ("STALE_INPUT", "STALE_INPUT"),
                    ("INVALID_CONFIGURATION", "INVALID_CONFIGURATION"),
                    ("PLUGIN_LOGIC_ERROR", "PLUGIN_LOGIC_ERROR"),
                    ("DATA_INTEGRITY_ERROR", "DATA_INTEGRITY_ERROR"),
                ], max_length=40)),
                ("error_details", models.JSONField(default=dict)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bar", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evaluation_jobs", to="market_streams.marketbar")),
                ("strategy_instance", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evaluation_jobs", to="strategies.strategyinstance")),
                ("strategy_run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="evaluation_jobs", to="strategies.strategyrun")),
                ("strategy_version", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evaluation_jobs", to="strategies.strategyversion")),
            ],
        ),
        migrations.AddConstraint(
            model_name="strategyevaluationjob",
            constraint=models.UniqueConstraint(
                fields=("strategy_instance", "strategy_version", "market_bar_id", "bar_version"),
                name="unique_strategy_eval_job",
            ),
        ),
        migrations.AddIndex(
            model_name="strategyevaluationjob",
            index=models.Index(
                fields=["status", "next_attempt_at", "created_at"],
                name="strategy_eval_job_queue_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="strategyevaluationjob",
            index=models.Index(fields=["status", "claimed_at"], name="strategy_eval_job_claim_idx"),
        ),
    ]
