import {useEffect,useMemo,useState} from 'react'
import {Activity,BookOpen,ChartCandlestick,ChevronRight,CircleDollarSign,FileClock,Gauge,Landmark,LayoutDashboard,RefreshCw,ShieldAlert,Terminal,Unplug,Zap,Radio,Scale,Waypoints} from 'lucide-react'
import {api} from './api'
import {ExposureChart} from './ExposureChart'
import {useTerminalStore} from './store'

const pages=[['Overview',LayoutDashboard],['Gateway',Unplug],['Accounts',Landmark],['Portfolio',BookOpen],['Strategies',ChartCandlestick],['Streaming',Radio],['Allocations',Waypoints],['Rebalancing',Scale],['Orders',FileClock],['Executions',CircleDollarSign],['Reconciliation',RefreshCw],['Risk',ShieldAlert],['System Logs',Terminal]] as const
const fmt=(x:any)=>x===null||x===undefined?'—':typeof x==='object'?JSON.stringify(x):String(x)
function Status({value}:{value:string}){const v=(value||'UNKNOWN').toUpperCase();const tone=/LIVE|CONNECTED|APPROVED|FILLED|HEALTHY|PAPER/.test(v)?'good':/BLOCK|REJECT|KILL|ERROR|DISCONNECT/.test(v)?'bad':'warn';return <span className={`status ${tone}`}><i/>{v}</span>}
function Panel({title,children,actions}:{title:string;children:React.ReactNode;actions?:React.ReactNode}){return <section className="panel"><header><span>{title}</span>{actions}</header><div className="panel-body">{children}</div></section>}
function Table({rows,columns}:{rows:any[];columns:string[]}){return <div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{c.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={r.id||i}>{columns.map(c=><td key={c} className={/id|price|quantity|cash|power|pnl|status|weight|commission/.test(c)?'mono':''}>{c==='status'?<Status value={fmt(r[c])}/>:fmt(r[c])}</td>)}</tr>):<tr><td colSpan={columns.length} className="empty">NO RECORDS</td></tr>}</tbody></table></div>}
function Overview(){const s=useTerminalStore();const account=s.accounts[0]||{};return <div className="grid"><Panel title="OPERATING STATE"><div className="metrics"><Metric label="MODE" value={s.system?.mode||'PAPER'} status/><Metric label="GATEWAY" value={s.gateway?.connected?'CONNECTED':'DISCONNECTED'} status/><Metric label="SYNC" value={s.gateway?.reconciled?'RECONCILED':'BLOCKED'} status/><Metric label="BREAKS" value={s.system?.material_breaks||0}/></div></Panel><Panel title="ACCOUNT SUMMARY"><div className="metrics"><Metric label="NAV" value={account.net_liquidation}/><Metric label="CASH" value={account.available_cash}/><Metric label="BUYING POWER" value={account.buying_power}/><Metric label="DAILY P&L" value={account.daily_pnl}/></div></Panel><Panel title="PORTFOLIO TRACE"><ExposureChart/></Panel><Panel title="ACTIVITY"><div className="metrics"><Metric label="OPEN ORDERS" value={s.orders.filter(x=>!['FILLED','CANCELLED','REJECTED'].includes(x.status)).length}/><Metric label="EXECUTIONS" value={s.executions.length}/><Metric label="POSITIONS" value={s.positions.length}/><Metric label="RISK BLOCKS" value={(s.risk?.decisions||[]).filter((x:any)=>x.decision!=='APPROVED').length}/></div></Panel></div>}
function Metric({label,value,status}:{label:string;value:any;status?:boolean}){return <div className="metric"><small>{label}</small><strong className="mono">{status?<Status value={fmt(value)}/>:fmt(value)}</strong></div>}
function Gateway(){const s=useTerminalStore();const reconnect=()=>api('gateway/',{method:'POST'}).then(s.refresh);const gateway=(import.meta.env.VITE_GATEWAY_PUBLIC_URL||'http://localhost:8080').replace(/\/$/,'');return <div className="grid"><Panel title="BROKER SESSION" actions={<button onClick={reconnect}><RefreshCw/>RECONNECT</button>}><div className="metrics"><Metric label="STATE" value={s.gateway?.connected?'CONNECTED':'DISCONNECTED'} status/><Metric label="MODE" value={s.gateway?.mode||'PAPER'} status/><Metric label="BROKER SYNC" value={s.gateway?.reconciled?'RECONCILED':'RECONCILING'} status/><Metric label="LAST CALLBACK" value={s.gateway?.last_callback}/></div></Panel><Panel title="OPERATOR CONSOLE"><p>Use noVNC only for IBKR authentication, 2FA, and Gateway settings.</p><a className="button" href={`${gateway}/novnc/vnc.html`} target="_blank" rel="noreferrer">OPEN noVNC <ChevronRight/></a></Panel></div>}
function Accounts(){const s=useTerminalStore();return <Panel title="BROKER ACCOUNTS"><Table rows={s.accounts} columns={['account_id','base_currency','net_liquidation','available_cash','buying_power','daily_pnl','is_reconciled']}/></Panel>}
function Portfolio(){const s=useTerminalStore();return <Panel title="IBKR POSITIONS"><Table rows={s.positions} columns={['account_id','symbol','asset_class','quantity','average_cost','market_price','market_value','currency','updated_at']}/></Panel>}
function Strategies(){
 const s=useTerminalStore();const [definitionKey,setDefinitionKey]=useState('');const [message,setMessage]=useState('');const [filter,setFilter]=useState('');
 const definition=s.strategyDefinitions.find(x=>x.key===(definitionKey||s.strategyDefinitions[0]?.key));
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const parameters:any={};
  Object.entries(definition?.parameter_schema?.properties||{}).forEach(([key,schema]:any)=>{const value=f.get(`parameter_${key}`);if(value!==null&&value!=='')parameters[key]=schema.type==='integer'?Number(value):schema.type==='number'?Number(value):value});
  try{const out:any=await api('strategy-instances/',{method:'POST',body:JSON.stringify({name:f.get('name'),definition_key:definition.key,
   ticker:String(f.get('ticker')).toUpperCase(),exchange:f.get('exchange'),portfolio_id:Number(f.get('portfolio_id')),timeframe:f.get('timeframe'),parameters,
   target_configuration:{target_weight:Number(f.get('target_weight')),capital_share:Number(f.get('capital_share')),priority:Number(f.get('priority'))},
   risk_policy_id:f.get('risk_policy_id')?Number(f.get('risk_policy_id')):null,order_policy_id:f.get('order_policy_id')?Number(f.get('order_policy_id')):null,
   execution_mode:f.get('execution_mode')||'SHADOW'})});setMessage(`CREATED — ${out.symbol} / ${out.definition_key} / V${out.version} / ${out.execution_mode}`);await s.refresh()}
  catch(error){setMessage(`BLOCKED — ${(error as Error).message}`)}};
 const act=async(id:number,name:string)=>{try{await api(`strategy-instances/${id}/${name}/`,{method:'POST',body:'{}'});await s.refresh()}catch(error){setMessage(`BLOCKED — ${(error as Error).message}`)}};
 const rows=s.strategyInstances.filter(x=>!filter||`${x.symbol} ${x.definition_key} ${x.state} ${x.execution_mode}`.toLowerCase().includes(filter.toLowerCase()));
 return <div className="grid strategy-grid"><Panel title="STRATEGY BUILDER // SHADOW DEFAULT"><form className="ticket strategy-builder" onSubmit={submit}>
  <label>INSTANCE NAME<input name="name" required placeholder="TSLA_RSI_5M"/></label><label>TICKER<input name="ticker" required placeholder="TSLA" list="ticker-list"/><datalist id="ticker-list">{s.instruments.map(x=><option key={x.id} value={x.symbol}/>)}</datalist></label>
  <label>EXCHANGE<select name="exchange"><option>SMART</option>{[...new Set(s.instruments.map(x=>x.exchange))].filter(x=>x!=='SMART').map(x=><option key={x}>{x}</option>)}</select></label>
  <label>PORTFOLIO<select name="portfolio_id" required>{s.portfolios.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
  <label>STRATEGY<select name="definition_key" value={definition?.key||''} onChange={e=>setDefinitionKey(e.target.value)}>{s.strategyDefinitions.map(x=><option key={x.key} value={x.key}>{x.name}</option>)}</select></label>
  <label>TIMEFRAME<select name="timeframe">{(definition?.supported_timeframes||['5m']).map((x:string)=><option key={x}>{x}</option>)}</select></label>
  {Object.entries(definition?.parameter_schema?.properties||{}).map(([key,schema]:any)=><label key={key}>{key.replaceAll('_',' ').toUpperCase()}{schema.enum?<select name={`parameter_${key}`} defaultValue={definition?.default_parameters?.[key]}>{schema.enum.map((x:string)=><option key={x}>{x}</option>)}</select>:<input name={`parameter_${key}`} type={schema.type==='number'||schema.type==='integer'?'number':'text'} step="any" min={schema.minimum} defaultValue={definition?.default_parameters?.[key]}/>}</label>)}
  <label>TARGET WEIGHT<input name="target_weight" type="number" min="-1" max="1" step="0.0001" defaultValue="0.05" required/></label><label>CAPITAL SHARE<input name="capital_share" type="number" min="0" max="1" step="0.01" defaultValue="1" required/></label>
  <label>PRIORITY<input name="priority" type="number" min="1" defaultValue="100" required/></label><label>RISK POLICY<select name="risk_policy_id"><option value="">PLATFORM DEFAULT</option>{(s.strategyPolicies?.risk_policies||[]).map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
  <label>ORDER POLICY<select name="order_policy_id"><option value="">PLATFORM DEFAULT</option>{(s.strategyPolicies?.order_policies||[]).map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>EXECUTION MODE<select name="execution_mode" defaultValue="SHADOW"><option>SHADOW</option><option>OBSERVE</option><option>PAPER</option></select></label>
  <div className="builder-summary"><span>INPUTS {(definition?.input_requirements||[]).map((x:any)=>`${x.name}(${Object.values(x.parameters||{}).join(',')})`).join(' + ')||'BAR'}</span><span>WARM-UP {Math.max(0,...(definition?.input_requirements||[]).map((x:any)=>x.warmup_bars))} BARS</span><span>LIVE UNAVAILABLE</span></div>
  <button type="submit"><Zap/>VALIDATE & CREATE</button><output>{message}</output></form></Panel>
  <Panel title="STRATEGY MONITOR" actions={<input className="filter-input" aria-label="Strategy filter" value={filter} onChange={e=>setFilter(e.target.value)} placeholder="FILTER TICKER / TYPE / STATE"/>}><Table rows={rows} columns={['name','symbol','conid','definition_key','version','timeframe','parameters','execution_mode','state','warmup_progress','warmup_required','last_final_bar','latest_indicators','latest_signal','current_target','attributed_quantity','active_order','last_fill','cooldown','block_reason']}/><div className="strategy-actions">{rows.map(x=><span key={x.id}><button disabled={x.enabled} onClick={()=>act(x.id,'enable')}>ENABLE {x.name}</button><button disabled={!x.enabled} onClick={()=>act(x.id,'pause')}>PAUSE</button><button onClick={()=>act(x.id,'flatten')}>FLATTEN TARGET</button></span>)}</div></Panel>
 </div>}
function Streaming(){const s=useTerminalStore();const health=s.streaming||{};return <div className="grid"><Panel title="DURABLE EVENT BUS"><div className="metrics"><Metric label="KAFKA" value={health.kafka_enabled?'ENABLED':'DISABLED'} status/><Metric label="OUTBOX PENDING" value={health.outbox_pending||0}/><Metric label="DEAD LETTER" value={health.dead_letter_count||0}/><Metric label="STALE PRICES" value={health.stale_instrument_count||0}/></div></Panel><Panel title="FLINK JOBS"><Table rows={health.flink?.jobs||[]} columns={['name','state','start-time','duration','last-modification']}/></Panel><Panel title="STREAM HEALTH"><Table rows={health.metrics||[]} columns={['component','metric','status','value','observed_at']}/></Panel><Panel title="RECOVERY POSTURE"><p>Kafka and Flink are private calculation infrastructure. Checkpoints and savepoints are durable; PostgreSQL remains financial truth. No broker controls are exposed here.</p></Panel></div>}
function Allocations(){const s=useTerminalStore();const [message,setMessage]=useState('');const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const out:any=await api('allocations/flows/',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({portfolio_id:Number(f.get('portfolio_id')),flow_type:f.get('flow_type'),amount:f.get('amount'),liquidation_policy:f.get('liquidation_policy')})});setMessage(`ALLOCATED — RUN ${out.id}`);await s.refresh()}catch(error){setMessage(`BLOCKED — ${(error as Error).message}`)}};return <div className="grid"><Panel title="PORTFOLIO FLOW // SHADOW"><form className="ticket" onSubmit={submit}><label>PORTFOLIO<select name="portfolio_id">{s.portfolios.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>FLOW TYPE<select name="flow_type"><option>DEPOSIT</option><option>WITHDRAWAL</option><option>INTERNAL_TRANSFER_IN</option><option>INTERNAL_TRANSFER_OUT</option></select></label><label>AMOUNT<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>LIQUIDATION<select name="liquidation_policy"><option>PROPORTIONAL</option><option>LOWEST_CONVICTION_FIRST</option><option>MOST_LIQUID_FIRST</option><option>LOWEST_COST_FIRST</option><option>PRIORITY_ORDER</option></select></label><button type="submit">CALCULATE FLOW</button><output>{message}</output></form></Panel><Panel title="ALLOCATION RUNS"><Table rows={s.allocationRuns} columns={['flow_type','amount','approved_amount','unallocated_amount','liquidation_policy','status','created_at']}/></Panel><Panel title="STRATEGY CAPITAL POLICY"><Table rows={s.allocationPolicies} columns={['portfolio','strategy','target_share','minimum_share','maximum_share','capacity','minimum_allocation','priority','enabled']}/></Panel></div>}
function Rebalancing(){const s=useTerminalStore();const [detail,setDetail]=useState<any>(null);const [sizing,setSizing]=useState<any>(null);const preview=async()=>{if(!s.portfolios[0])return;const out=await api<any>('rebalancing/preview/',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({portfolio_id:s.portfolios[0].id,trigger:'MANUAL'})});setDetail(out);await s.refresh()};const open=async(id:number)=>setDetail(await api<any>(`rebalancing/runs/${id}/`));const size=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setSizing(await api<any>('position-sizing/preview/',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({portfolio_id:Number(f.get('portfolio_id')),instrument_id:Number(f.get('instrument_id')),side:f.get('side'),target_quantity:f.get('target_quantity'),entry_price:f.get('entry_price'),stop_price:f.get('stop_price')||null,adv:f.get('adv')})}))};return <div className="grid"><Panel title="REBALANCE POLICY" actions={<button onClick={preview}><Scale/>SHADOW PREVIEW</button>}><Table rows={s.rebalancePolicies} columns={['portfolio_id','instrument_drift_threshold','portfolio_drift_threshold','minimum_trade_notional','maximum_turnover','cash_buffer_percent','sell_before_buy','mode']}/></Panel><Panel title="REBALANCE RUNS"><Table rows={s.rebalanceRuns} columns={['trigger','mode','phase','status','total_drift','planned_turnover','created_at']}/><div className="strategy-actions">{s.rebalanceRuns.slice(0,5).map(x=><button key={x.id} onClick={()=>open(x.id)}>DETAIL {x.id}</button>)}</div></Panel><Panel title="TARGET / DRIFT / SUPPRESSION"><Table rows={detail?.targets||[]} columns={['instrument_id','current_weight','target_weight','drift','current_quantity','target_quantity','trade_quantity','reference_price','suppressed','suppression_reason','rank']}/></Panel><Panel title="SINGLE-STOCK SIZING DETAILS"><form className="ticket" onSubmit={size}><label>PORTFOLIO<select name="portfolio_id">{s.portfolios.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>INSTRUMENT<select name="instrument_id">{s.instruments.map(x=><option key={x.id} value={x.id}>{x.symbol}</option>)}</select></label><label>SIDE<select name="side"><option>BUY</option><option>SELL</option></select></label><label>TARGET QTY<input name="target_quantity" type="number" min="0" step="any" required/></label><label>ENTRY PRICE<input name="entry_price" type="number" min="0.0001" step="any" required/></label><label>STOP PRICE<input name="stop_price" type="number" min="0" step="any"/></label><label>AVG VOLUME<input name="adv" type="number" min="0" step="any" required/></label><button type="submit">PREVIEW SIZE</button></form>{sizing&&<Table rows={[sizing]} columns={['target_quantity','risk_quantity','weight_quantity','liquidity_quantity','cash_quantity','broker_quantity','approved_quantity','binding_constraint','rejected_reason']}/>}</Panel></div>}
function Orders(){const s=useTerminalStore();const [message,setMessage]=useState('');const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const quantity=Number(f.get('quantity'));if(quantity<=0){setMessage('Quantity must be greater than zero');return}setMessage('VALIDATED — RUNNING PRE-TRADE RISK');try{const result:any=await api('orders/',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({portfolio_id:Number(f.get('portfolio_id')),instrument_id:Number(f.get('instrument_id')),side:f.get('side'),order_type:f.get('order_type'),quantity:f.get('quantity'),reference_price:f.get('reference_price'),time_in_force:f.get('time_in_force')})});setMessage(`${result.decision||'ACCEPTED'} — ${result.internal_id}`);await s.refresh()}catch(error){setMessage(`BLOCKED — ${(error as Error).message}`)}};const cancel=async(id:string)=>{await api(`orders/${id}/cancel/`,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:'{}'});await s.refresh()};const modify=async(id:string,current:any)=>{const quantity=window.prompt('New total quantity',String(current));if(!quantity)return;await api(`orders/${id}/`,{method:'PATCH',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({quantity})});await s.refresh()};const active=s.orders.filter(x=>['QUEUED','SUBMITTED','ACKNOWLEDGED','PARTIALLY_FILLED'].includes(x.status));return <div className="grid"><Panel title="ORDER TICKET // PRE-TRADE RISK"><form onSubmit={submit} className="ticket"><label>PORTFOLIO<select name="portfolio_id" required>{s.portfolios.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>INSTRUMENT<select name="instrument_id" required>{s.instruments.map(x=><option key={x.id} value={x.id}>{x.symbol} / {x.exchange}</option>)}</select></label><label>SIDE<select name="side"><option>BUY</option><option>SELL</option></select></label><label>TYPE<select name="order_type"><option>MKT</option><option>LMT</option><option>STP</option><option>STP_LMT</option></select></label><label>QUANTITY<input name="quantity" type="number" min="0" step="any" required/></label><label>REFERENCE PRICE<input name="reference_price" type="number" min="0" step="any" required/></label><label>TIF<select name="time_in_force"><option>DAY</option><option>GTC</option></select></label><button type="submit">SUBMIT TO RISK</button><output>{message}</output></form></Panel><Panel title="IBKR ORDER BLOTTER"><Table rows={s.orders} columns={['account_id','symbol','side','order_type','status','quantity','filled_quantity','average_fill_price','broker_order_id','internal_id','updated_at']}/><div className="strategy-actions">{active.map(x=><span key={x.internal_id}><button onClick={()=>modify(x.internal_id,x.quantity)}>MODIFY {x.internal_id.slice(0,8)}</button><button className="danger" onClick={()=>cancel(x.internal_id)}>CANCEL</button></span>)}</div></Panel></div>}
function Executions(){const s=useTerminalStore();return <Panel title="IBKR EXECUTION LEDGER"><Table rows={s.executions} columns={['account_id','symbol','execution_id','order_id','quantity','price','commission','currency','executed_at']}/></Panel>}
function Reconciliation(){const s=useTerminalStore();return <div className="grid"><Panel title="RECONCILIATION RUNS"><Table rows={s.reconciliation?.runs||[]} columns={['trigger','status','started_at','completed_at']}/></Panel><Panel title="UNRESOLVED BREAKS"><Table rows={s.reconciliation?.breaks||[]} columns={['category','severity','material','resolved','created_at']}/></Panel></div>}
function Risk(){const s=useTerminalStore();const [confirm,setConfirm]=useState(false);const kill=()=>api('risk/',{method:'POST',body:JSON.stringify({scope:'GLOBAL',enabled:true,reason:'Frontend operator action'})}).then(()=>{setConfirm(false);s.refresh()});return <div className="grid"><Panel title="KILL SWITCHES" actions={<button className="danger" onClick={()=>setConfirm(true)}><ShieldAlert/>ENGAGE GLOBAL</button>}><Table rows={s.risk?.kill_switches||[]} columns={['scope','scope_id','enabled','reason','updated_at']}/>{confirm&&<div className="confirm"><strong>CONFIRM GLOBAL TRADING HALT</strong><button className="danger" onClick={kill}>CONFIRM KILL SWITCH</button><button onClick={()=>setConfirm(false)}>CANCEL</button></div>}</Panel><Panel title="RISK DECISIONS"><Table rows={s.risk?.decisions||[]} columns={['check_name','decision','reason','requested_quantity','approved_quantity','created_at']}/></Panel></div>}
function Logs(){const s=useTerminalStore();return <Panel title="SYSTEM / AUDIT LOG"><Table rows={s.logs} columns={['created_at','event_type','actor','aggregate_type','aggregate_id']}/></Panel>}
const screens:Record<string,()=>JSX.Element>={'Overview':Overview,'Gateway':Gateway,'Accounts':Accounts,'Portfolio':Portfolio,'Strategies':Strategies,'Streaming':Streaming,'Allocations':Allocations,'Rebalancing':Rebalancing,'Orders':Orders,'Executions':Executions,'Reconciliation':Reconciliation,'Risk':Risk,'System Logs':Logs}
export default function App(){const [page,setPage]=useState('Overview');const s=useTerminalStore();useEffect(()=>{s.refresh();const id=setInterval(s.refresh,15000);return()=>clearInterval(id)},[]);const Screen=useMemo(()=>screens[page],[page]);return <div className="shell"><aside><div className="brand"><Gauge/><div><b>FINFLOCK</b><span>EXECUTION ENGINE</span></div></div><nav aria-label="Trading sections">{pages.map(([name,Icon])=><button key={name} className={page===name?'active':''} onClick={()=>setPage(name)}><Icon/>{name}<ChevronRight/></button>)}</nav><div className="sidebar-foot"><Status value={s.system?.mode||'PAPER'}/><span>NO DIRECT TWS ACCESS</span></div></aside><main><div className="topbar"><div><small>TRADING /</small><h1>{page}</h1></div><div className="top-state"><Activity/><span>API</span><Status value={s.error?'DEGRADED':'HEALTHY'}/><button aria-label="Refresh data" onClick={s.refresh}><RefreshCw className={s.loading?'spin':''}/></button></div></div>{s.error&&<div className="alert">DATA CHANNEL DEGRADED — {s.error}</div>}<Screen/></main></div>}
