from abc import ABC, abstractmethod

class BrokerAdapter(ABC):
    @abstractmethod
    def connect(self): ...
    @abstractmethod
    def disconnect(self): ...
    @abstractmethod
    def is_connected(self): ...
    @abstractmethod
    def search_contracts(self, query): ...
    @abstractmethod
    def qualify_contract(self, payload): ...
    @abstractmethod
    def place_order(self, payload): ...
    @abstractmethod
    def modify_order(self, payload): ...
    @abstractmethod
    def cancel_order(self, payload): ...
    @abstractmethod
    def refresh_state(self): ...
    @abstractmethod
    def wait(self, seconds): ...
