# Generated by Django 5.1.7 on 2026-07-11 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KillSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=32)),
                ('scope_id', models.CharField(blank=True, max_length=64)),
                ('enabled', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope', 'scope_id'), name='unique_kill_switch')],
            },
        ),
        migrations.CreateModel(
            name='RiskCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_name', models.CharField(max_length=64)),
                ('decision', models.CharField(choices=[('APPROVED', 'APPROVED'), ('RESIZED', 'RESIZED'), ('HELD', 'HELD'), ('REJECTED', 'REJECTED')], max_length=16)),
                ('reason', models.CharField(max_length=255)),
                ('requested_quantity', models.DecimalField(decimal_places=8, max_digits=24)),
                ('approved_quantity', models.DecimalField(decimal_places=8, max_digits=24)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_checks', to='oms.orderintent')),
            ],
        ),
    ]
