# Generated by Django 5.1.7 on 2026-07-14 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0005_allocationrun_optimization_run_and_more'),
        ('portfolio_optimization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliooptimizationrun',
            name='application_idempotency_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='portfoliooptimizationrun',
            name='application_status',
            field=models.CharField(choices=[('NOT_APPLIED', 'NOT_APPLIED'), ('APPLYING', 'APPLYING'), ('APPLIED', 'APPLIED')], default='NOT_APPLIED', max_length=24),
        ),
        migrations.AddField(
            model_name='portfoliooptimizationrun',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliooptimizationrun',
            name='applied_rebalance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_optimization', to='allocation.rebalancerun'),
        ),
    ]
