# Generated by Django 5.1.7 on 2026-07-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimization', '0003_operation_idempotency_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliooptimizationrun',
            name='application_status',
            field=models.CharField(choices=[('NOT_APPLIED', 'NOT_APPLIED'), ('QUEUED', 'QUEUED'), ('APPLYING', 'APPLYING'), ('APPLIED', 'APPLIED'), ('FAILED', 'FAILED')], default='NOT_APPLIED', max_length=24),
        ),
    ]
